name: Benchmark tags
on:
  push:
    tags:
      - v*

jobs:
    benchmark-tag:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
        - name: Install deno
          uses: denolib/setup-deno@master
          with:
            deno-version: 1.4.0
        - name: Set output
          run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
        - name: Bench It
          run: deno run --allow-hrtime --allow-write ./benchmarks/pr_benchmarks.ts --save-history --id=${{ env.RELEASE_VERSION }}
        - uses: EndBug/add-and-commit@v4
          with:
            message: 'Benchmark history for ${{ env.RELEASE_VERSION }}'
          env:
            # This is necessary in order to push a commit to the repo
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
